BEGIN;

CREATE TABLE IF NOT EXISTS popular_posts (
    post_id UUID PRIMARY KEY REFERENCES blog_posts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
