BEGIN;
-- テーブルの作成
CREATE TABLE IF NOT EXISTS images (
    id UUID PRIMARY KEY,
    file_name VARCHAR(255),
    file_path VARCHAR(255) NOT NULL UNIQUE,
    caption VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS text_styles (
    id UUID PRIMARY KEY,
    style_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blog_posts (
    id UUID PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    thumbnail_image_id UUID NOT NULL REFERENCES images(id),
    post_date DATE NOT NULL,
    last_update_date DATE NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_contents (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL REFERENCES blog_posts(id),
    content_type VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS image_blocks (
    id UUID PRIMARY KEY REFERENCES post_contents(id),
    image_id UUID NOT NULL REFERENCES images(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS heading_blocks (
    id UUID PRIMARY KEY REFERENCES post_contents(id),
    heading_level SMALLINT NOT NULL,
    text_content VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paragraph_blocks (
    id UUID PRIMARY KEY REFERENCES post_contents(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rich_texts (
    id UUID PRIMARY KEY,
    paragraph_block_id UUID NOT NULL REFERENCES paragraph_blocks(id),
    text_content VARCHAR(1000) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rich_text_styles (
    style_id UUID NOT NULL REFERENCES text_styles(id),
    rich_text_id UUID NOT NULL REFERENCES rich_texts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (style_id, rich_text_id)
);

COMMIT;
