BEGIN;

CREATE TABLE IF NOT EXISTS top_tech_pick_post (
    id UUID PRIMARY KEY,
    post_id UUID NOT NULL UNIQUE REFERENCES blog_posts(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;