CREATE TABLE IF NOT EXISTS code_blocks (
    id UUID PRIMARY KEY REFERENCES post_contents(id),
    title VARCHAR(200) NOT NULL,
    code TEXT NOT NULL,
    lang VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
