{{- if not .Values.production }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e2e.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "e2e.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "e2e.appname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "e2e.appname" . }}
        {{- include "blog-chart.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- if .Values.e2e.pod.imagePullSecret }}
        - name: {{ .Values.e2e.pod.imagePullSecret }}
        {{- end }}
      containers:
        - name: {{ include "e2e.appname" . }}
          image: "{{ .Values.e2e.pod.imageRepository }}:{{ .Values.e2e.pod.imageTag }}"
          imagePullPolicy: {{ .Values.e2e.pod.imagePullPolicy }}
          resources:
            limits:
              memory: {{ .Values.e2e.pod.memoryLimit }}
              cpu: {{ .Values.e2e.pod.cpuLimit }}
            requests:
              memory: {{ .Values.e2e.pod.memoryRequest }}
              cpu: {{ .Values.e2e.pod.cpuRequest }}
          ports:
            - containerPort: 4000
          env:
            - name: TEST_TARGET_URL
              value: {{ .Values.e2e.pod.env.TEST_TARGET_URL }}
            - name: ADMIN_URL
              value: {{ .Values.e2e.pod.env.ADMIN_URL }}
            - name: DISPLAY
              value: :0
          volumeMounts:
            - mountPath: /tmp/.X11-unix
              name: unix-domain-socket
      volumes:
        - name: unix-domain-socket
          hostPath:
            path: /tmp/.X11-unix
{{- end }}
