# これは bacon ツール用の設定ファイルです
#
# 設定に関する詳細なヘルプ:
#   https://dystroy.org/bacon/config/
#
# 現在のデフォルトは以下で確認できます
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml


[jobs.run-api]
command = ["cargo", "run", "-p", "blog-api-v2"]
watch = ["api_v2", "common"]
need_stdout = true
on_change_strategy = "kill_then_restart"
# 増分コンパイルを最大限活用
[env]
CARGO_INCREMENTAL = "1"
