apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web.appname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web.appname" . }}
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "web.appname" . }}
          image: {{ .Values.web.pod.imageName }}
          imagePullPolicy: {{ .Values.web.pod.imagePullPolicy }}
          # (デバッグ用)コンテナが起動した後に終了しないようにする
          command: ["sleep", "infinity"]
          resources:
            limits:
              memory: {{ .Values.web.pod.memoryLimit }}
              cpu: {{ .Values.web.pod.cpuLimit }}
            requests:
              memory: {{ .Values.web.pod.memoryRequest }}
              cpu: {{ .Values.web.pod.cpuRequest }}
          ports:
            - containerPort: {{ .Values.web.pod.containerPort }}