apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  rules:
    - {{- if .Values.webHost }}
      host: {{ .Values.webHost }}
      {{- end }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ include "web.appname" . }}
              port:
                number: 80