apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "web.appname" . }}
