apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: forbid-external-access-to-e2e
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: e2e
  policyTypes:
  - Egress

  # e2e 環境からは外部へのアクセスを禁止する
  egress:
    - to:
      - podSelector: {}
      - namespaceSelector: {}
