apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: addresspool
  namespace: metallb-system
spec:
  addresses:
    - 127.0.0.1-127.0.0.1
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: addresspool
  namespace: metallb-system
spec:
  ipAddressPools:
    - addresspool
