apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-lb
spec:
  addresses:
  - 192.168.0.1-192.168.0.1
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-lb
spec:
  ipAddressPools:
  - default-lb
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: blog-worker