name: "Docker イメージのビルド・プッシュのセットアップ"
description: "Buildx のセットアップ, ghcr.io へのログインを行います。"
runs:
  using: "composite"
  steps:
    - name: "Set up buildx"
      uses: docker/setup-buildx-action@v3

    - name: "Login to ghcr.io"
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
