apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web.appname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web.appname" . }}
        {{- include "blog-chart.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- if .Values.web.pod.imagePullSecret }}
        - name: {{ .Values.web.pod.imagePullSecret }}
        {{- end }}
      containers:
        - name: {{ include "web.appname" . }}
          image: "{{ .Values.web.pod.imageRepository }}:{{ .Values.web.pod.imageTag }}"
          imagePullPolicy: {{ .Values.web.pod.imagePullPolicy }}
          resources:
            limits:
              memory: {{ .Values.web.pod.memoryLimit }}
              cpu: {{ .Values.web.pod.cpuLimit }}
            requests:
              memory: {{ .Values.web.pod.memoryRequest }}
              cpu: {{ .Values.web.pod.cpuRequest }}
          ports:
            - containerPort: {{ .Values.web.pod.containerPort }}
