apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: master
    {{- if .Values.web.ingress.onAuth }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.web.ingress.authSecret }}
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end }}
spec:
  rules:
    - {{- if .Values.web.ingress.host }}
      host: {{ .Values.web.ingress.host }}
      {{- end }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /
          backend:
            service:
              name: {{ include "web.appname" . }}
              port:
                number: {{ .Values.web.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web.appname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}-api
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: minion
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/auth-type: "basic"
    # nginx.ingress.kubernetes.io/auth-secret: "blog-basic-auth"
    # nginx.ingress.kubernetes.io/auth-realm: "Staging Auth"
spec:
  rules:
  - {{- if .Values.web.ingress.host }}
    host: {{ .Values.web.ingress.host }}
    {{- end }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/v2(/|$)(.*)
        backend:
          service:
            name: {{ include "api_v2.appname" . }}
            port:
              number: {{ .Values.api_v2.service.port }}
      - pathType: ImplementationSpecific
        path: /api(/|$)(.*)
        backend:
          service:
            name: {{ include "api.appname" . }}
            port:
              number: {{ .Values.api.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "web.appname" . }}-api-admin
  labels:
    app.kubernetes.io/name: {{ include "web.appname" . }}-api-admin
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: minion
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - {{- if .Values.web.ingress.host }}
    host: {{ .Values.web.ingress.host }}
    {{- end }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/admin(/|$)(.*)
        backend:
          service:
            name: deny-404
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deny-404
spec:
  selector: { app: dummy }   # どの Pod も選ばれない
  ports:
    - protocol: TCP
      port: 80