apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgres.appname" . }}
  replicas: {{ .Values.postgres.statefulSet.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres.appname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgres.appname" . }}
        {{- include "blog-chart.labels" . | nindent 8 }}
    spec:
      # postgres ユーザーが 999:999 なので、それに合わせる
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
      imagePullSecrets:
        {{- if .Values.postgres.pod.imagePullSecret }}
        - name: {{ .Values.postgres.pod.imagePullSecret }}
        {{- end }}
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/postgresql/data
              chown -R 999:999 /var/lib/postgresql/data
              chmod 700 /var/lib/postgresql/data
          securityContext:
            runAsUser: 0 # root で実行
          volumeMounts:
            - name: {{ include "postgres.appname" . }}-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: {{ include "postgres.appname" . }}
          image: "{{ .Values.postgres.pod.imageRepository }}:{{ .Values.postgres.pod.imageTag }}"
          imagePullPolicy: {{ .Values.postgres.pod.imagePullPolicy }}
          resources:
            limits:
              memory: {{ .Values.postgres.pod.memoryLimit }}
              cpu: {{ .Values.postgres.pod.cpuLimit }}
            requests:
              memory: {{ .Values.postgres.pod.memoryRequest }}
              cpu: {{ .Values.postgres.pod.cpuRequest }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.secret.name" . }}
                  key: user_password
            - name: POSTGRES_DB
              value: blog
          ports:
            - containerPort: {{ .Values.postgres.pod.containerPort }}
          volumeMounts:
            - name: {{ include "postgres.appname" . }}-data
              # postgresql のデフォルトのデータディレクトリ
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "postgres.appname" . }}-data
      spec:
        {{- if .Values.postgres.pvc.volumeName }}
        volumeName: {{ .Values.postgres.pvc.volumeName }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.statefulSet.storage }}
