apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "api.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - {{- if .Values.api.ingress.host }}
      host: {{ .Values.api.ingress.host }}
      {{- end }}
      http:
        paths:
        - pathType: {{ .Values.api.ingress.pathType }}
          path: {{ .Values.api.ingress.path }}
          backend:
            service:
              name: {{ include "api.appname" . }}
              port:
                number: {{ .Values.api.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.appname" . }}-admin
  labels:
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "api-admin-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  rules:
    - {{- if .Values.api.ingress.host }}
      host: {{ .Values.api.ingress.host }}
      {{- end }}
      http:
        paths:
          - pathType: Prefix
            path: /admin(/|$)(.*) # /admin だけマッチ
            backend:
              service:
                name: {{ include "api.appname" . }}
                port:
                  number: {{ .Values.api.service.port }}