web:
  ingress:
    # host が空文字列の場合は rules に含まれない
    host: "blog.example"
    onAuth: false
    authSecret: ""
  deployment:
    replicas: 1
  pod:
    imageRepository: "web"
    imageTag: "v0.0.0"
    imagePullSecret: ""
    # Always だとリモートから pull してしまう
    # 今回はローカルのイメージを使うために Never にしている
    imagePullPolicy: Never
    memoryLimit: "2000Mi"
    cpuLimit: "1000m"
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    containerPort: 3000
    env:
      NEXT_PUBLIC_API_URL: "http://blog.example/api"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    # ここから下の設定は type:ClusterIP の場合は関係ないが、
    # 一応デフォルト値は入れておく
    nodePort: 30080
    loadBalancerIP: "192.168.1.100"
    externalTrafficPolicy: Local
admin:
  ingress:
    # host が空文字列の場合は rules に含まれない
    host: "admin.blog.example"
    onAuth: false
    authSecret: ""
  deployment:
    replicas: 1
  pod:
    imageRepository: "blog-admin"
    imageTag: "v0.0.0"
    imagePullSecret: ""
    # Always だとリモートから pull してしまう
    # 今回はローカルのイメージを使うために Never にしている
    imagePullPolicy: Never
    memoryLimit: "3500Mi"
    cpuLimit: "1000m"
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    containerPort: 3000
    env:
      NEXT_PUBLIC_API_URL: "http://admin.blog.example/api"
      NEXT_PUBLIC_WEB_URL: "http://blog.example"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    # ここから下の設定は type:ClusterIP の場合は関係ないが、
    # 一応デフォルト値は入れておく
    nodePort: 30080
    loadBalancerIP: "192.168.1.100"
    externalTrafficPolicy: Local
api:
  deployment:
    replicas: 1
  pod:
    imageRepository: "api"
    imageTag: "v0.0.0"
    imagePullSecret: ""
    # Always だとリモートから pull してしまう
    # 今回はローカルのイメージを使うために Never にしている
    imagePullPolicy: Never
    memoryLimit: "1500Mi"
    cpuLimit: "750m"
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    containerPort: 8000
    apiTest:
      imageRepository: "api-test"
      imageTag: "v0.0.0"
      imagePullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
    # ここから下の設定は type:ClusterIP の場合は関係ないが、
    # 一応デフォルト値は入れておく
    nodePort: 30080
    loadBalancerIP: "192.168.1.100"
    externalTrafficPolicy: Local
postgres:
  statefulSet:
    replicas: 1
    storage: "1Gi"
  pvc:
    volumeName: ""
  pod:
    imageRepository: "postgres"
    imageTag: "v0.0.0"
    imagePullSecret: ""
    # Always だとリモートから pull してしまう
    # 今回はローカルのイメージを使うために Never にしている
    imagePullPolicy: Never
    memoryLimit: "1500Mi"
    cpuLimit: "750m"
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    containerPort: 5432
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
    # ここから下の設定は type:ClusterIP の場合は関係ないが、
    # 一応デフォルト値は入れておく
    nodePort: 30080
    loadBalancerIP: "192.168.1.100"
    externalTrafficPolicy: Local
e2e:
  pod:
    imageRepository: "e2e"
    imageTag: "v0.0.0"
    imagePullSecret: ""
    imagePullPolicy: Never
    env:
      TEST_TARGET_URL: "http://blog.example"
      ADMIN_URL: "http://admin.blog.example"
    memoryLimit: "5000Mi"
    cpuLimit: "4000m"
    memoryRequest: "250Mi"
    cpuRequest: "100m"

  # 開発環境では coreDNS で名前解決を行うため、空の値を指定
  hostAliases:
    ip: ""
    hostnames: []
production: false
