apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "admin.appname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admin.appname" . }}
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: master
    {{- if .Values.admin.ingress.onAuth }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.admin.ingress.authSecret }}
    nginx.ingress.kubernetes.io/auth-realm: "Staging Auth"
    {{- end }}
spec:
  rules:
    - {{- if .Values.admin.ingress.host }}
      host: {{ .Values.admin.ingress.host }}
      {{- end }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ include "admin.appname" . }}
              port:
                number: {{ .Values.admin.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "admin.appname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "admin.appname" . }}-api
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: minion
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - {{- if .Values.admin.ingress.host }}
    host: {{ .Values.admin.ingress.host }}
    {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: /api(/|$)(.*)
        backend:
          service:
            name: {{ include "api.appname" . }}
            port:
              number: {{ .Values.api.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "admin.appname" . }}-api-admin
  labels:
    app.kubernetes.io/name: {{ include "admin.appname" . }}-api-admin
    {{- include "blog-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/mergeable-type: minion
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/auth-type: "basic"
    # nginx.ingress.kubernetes.io/auth-secret: "blog-basic-auth"
    # nginx.ingress.kubernetes.io/auth-realm: "Staging Auth"
spec:
  rules:
  - {{- if .Values.admin.ingress.host }}
    host: {{ .Values.admin.ingress.host }}
    {{- end }}
    http:
      paths:
      - pathType: Prefix
        path: /api/admin/(/|$)(.*)
        backend:
          service:
            name: {{ include "api.appname" . }}
            port:
              number: {{ .Values.api.service.port }}