name: "e2e テストの実行"

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # 普通に実行すると各種ツールのインストールや DockerImage の読み込みでリソース不足に陥るため、
      # 以下のアクションで事前にディスク領域を解放
      # - name: "action の実行環境のディスク領域を解放"
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: false

      - name: "リポジトリのチェックアウト"
        uses: actions/checkout@v4

      - name: "buildx のセットアップ"
        uses: docker/setup-buildx-action@v3

      - name: "kubectl のセットアップ"
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.27.14"

      - name: "microk8s のセットアップ"
        run:
          make mk8s-setup

      - run: which mkdir

      - name: "microk8s のグループをセットアップ"
        shell: bash
        run:
          sudo -E usermod -a -G microk8s $USER && \
          mkdir -p ~/.kube && \
          chmod 0700 ~/.kube && \
          newgrp microk8s # グループの適用。su だとシェルが変わるのでこちらが適切

      - name: "microk8s の準備が完了するまで待機"
        run:
          microk8s status --wait-ready

      - name: "microk8s をローカルクラスタに統合"
        run:
          make mk8s-make-local-cluster

      - name: "Helm のセットアップ"
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.3

      - name: "Chart のインストール"
        run: |
          make helm-install

      - name: "image の build"
        run: |
          make docker-image-build

      - name: "image の load"
        run: |
          make mk8s-import-image image_name=web:v0.0.0
          make mk8s-import-image image_name=api:v0.0.0
          make mk8s-import-image image_name=e2e:v0.0.0

      - name: "e2e テストを実行する Deployment リソースが準備できるまで待機"
        run: |
          kubectl rollout status deployment/e2e --timeout=120s

      - name: "テスト対象の Deployment リソースが準備できるまで待機"
        run: |
          kubectl rollout status deployment/web --timeout=120s

      - name: "e2e テストを実行する"
        run: |
          make e2e-run-ci

      - name: "MicroK8s クラスタを削除"
        run: |
          sudo snap remove microk8s
