name: "単体テスト&静的チェックの実行"

on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - "PBI*"

env:
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
  NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: "リポジトリのチェックアウト"
        uses: actions/checkout@v4

      - name: "node のセットアップ"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9

      - name: "モジュールの install"
        run: make frontend-install

      - name: "一部パッケージのトランスパイル"
        run: make frontend-tsc

      - name: "単体テストの実行"
        run: make frontend-test-unit
  check:
    runs-on: ubuntu-latest

    steps:
      - name: "リポジトリのチェックアウト"
        uses: actions/checkout@v4

      - name: "node のセットアップ"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9.9

      - name: "モジュールの install"
        run: make frontend-install

      - name: "一部パッケージのトランスパイル"
        run: make frontend-tsc

      - name: "静的チェックの実行"
        run: make frontend-check
